// Generated by CoffeeScript 1.4.0
(function() {

  this.ContentFactory = (function() {

    function ContentFactory() {}

    ContentFactory.make = function(args, def_html) {
      var content, defs, key, val, _ref;
      defs = {
        html: def_html,
        before_route: [],
        before: [],
        complete: [],
        menu: null,
        context: 'show_content'
      };
      content = {};
      for (key in defs) {
        val = defs[key];
        if (args[key] != null) {
          content[key] = copy(args[key]);
        } else {
          content[key] = val;
        }
      }
      content.html = (_ref = typeof content.html === "function" ? content.html() : void 0) != null ? _ref : content.html;
      if (content.html == null) {
        content.error_404 = true;
      }
      return content;
    };

    return ContentFactory;

  })();

}).call(this);
