// Generated by CoffeeScript 1.4.0
(function() {

  this.Config = {
    version: '2.0.0',
    production: true,
    remote_web_service: "http://wemoveapp.com/",
    local_web_service: "http://192.168.1.31/we_move_web/"
  };

}).call(this);
