// Generated by CoffeeScript 1.4.0
(function() {

  this.Phonegap = (function() {

    function Phonegap() {
      $.ajaxSetup({
        data: {
          phonegap: 'phonegap'
        }
      });
      if (typeof FastClick !== "undefined" && FastClick !== null) {
        FastClick.attach(document.body);
      }
    }

    return Phonegap;

  })();

}).call(this);
