// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  this.init = function(mode) {
    var closure;
    closure = function() {};
    new Reloader();
    Setup.core();
    Setup.models();
    Setup.layout();
    Setup.cache();
    return $('#wrapper').html(Views.hello_cohsa());
  };

  Setup.initialize_function(init);

}).call(this);
