// Generated by CoffeeScript 1.4.0
(function() {

  this.InterfaceBindings = {
    menu: {
      movers: function() {
        $('#movers_requests').click(function() {
          return _movers.show_requests();
        });
        return $('#movers_friends').click(function() {
          return _movers.show_friends();
        });
      },
      settings: function() {
        $('#we_move_about').click(function(e) {
          return new ListView({
            html: JSV.settings.about(),
            title: "About We Move",
            add_class: 'footer'
          });
        });
        $('#we_move_contact').click(function(e) {
          return new ListView({
            html: JSV.settings.contact(),
            title: "Contact",
            add_class: 'footer'
          });
        });
        return $('#we_move_legal').click(function(e) {
          return new ListView({
            html: JSV.settings.legal(),
            title: "Terms and Conditions",
            add_class: 'footer'
          });
        });
      }
    },
    events: {
      view_event_more_options: function() {}
    },
    user: {
      view_user_more_options: function() {},
      view: function() {
        return $('#view_user_more_options').click(function(e) {
          return _user.view_more_options();
        });
      }
    },
    user: {
      login: function() {
        return $('#login_with_facebook').live('click', _facebook.login);
      }
    }
  };

}).call(this);
