// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Database = (function() {

    function Database() {
      this.unset = __bind(this.unset, this);

      this.get = __bind(this.get, this);

      this.set = __bind(this.set, this);
      this.debug = is_debug('database');
    }

    Database.prototype.filterQuery = function() {};

    Database.prototype.processQuery = function() {
      var item;
      item = localStorage.getItem(this.q);
      if (item != null) {
        return JSON.parse(item);
      }
      return null;
    };

    Database.prototype.set = function(key, val) {
      if (val == null) {
        val = null;
      }
      if (this.debug) {
        console.log("DB: setItem ", key, val);
      }
      return localStorage.setItem(key, JSON.stringify(val));
    };

    Database.prototype.get = function(q) {
      this.q = q;
      if (this.debug) {
        console.log("DB: getItem ", this.q);
      }
      this.filterQuery();
      return this.processQuery();
    };

    Database.prototype.unset = function(key) {
      return localStorage.removeItem(key);
    };

    return Database;

  })();

}).call(this);
