// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    replace: function(content) {
      var debug, html, _t;
      debug = is_debug('replacer');
      _t = Transitioner.get();
      if (is_string(content)) {
        html = content;
      } else {
        html = content.html;
      }
      return this.each(function(i, _container) {
        var container, n_el, o_el;
        container = $(_container);
        n_el = $(html);
        o_el = $("#" + container.attr('data-content'));
        if (debug) {
          console.log('[Replacer] context:', content.context);
        }
        if (content.context === 'show_map') {
          _t.slide_down(o_el, n_el, container, content.before, content.complete);
        } else if (content.context === 'show_content') {
          if (_nav.is_map()) {
            _t.slide_up(o_el, n_el, container, content.before, content.complete);
          } else {
            _t.slide_left(o_el, n_el, container, content.before, content.complete);
          }
        } else if (content.context === 'back') {
          _t.slide_right(o_el, n_el, container, content.before, content.complete);
        } else if (content.context === 'refresh') {
          _t.cross_fade(o_el, n_el, container, content.before, content.complete);
        }
        return container.attr('data-content', n_el.attr('id'));
      });
    }
  });

}).call(this);
