// Generated by CoffeeScript 1.4.0
(function() {

  this.Dependency = {
    dependencies: {},
    registered_dependencies: {},
    up: function(dependency) {
      var elem, _i, _len, _ref, _results;
      this.dependencies[dependency] = true;
      _ref = this.registered_dependencies[dependency];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elem = _ref[_i];
        _results.push(this.call_if_it_is_time(elem));
      }
      return _results;
    },
    down: function(dependency) {
      return delete this.dependencies[dependency];
    },
    call_if_it_is_time: function(elem) {
      var dependency, _i, _len, _ref;
      _ref = elem.dependency_list;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        dependency = _ref[_i];
        if (!this.dependencies[dependency]) {
          return;
        }
      }
      elem.callback();
      return elem.callback = function() {
        return console.log('callback already called');
      };
    },
    register_dependency: function(callback, dependency_list) {
      var dependency, elem, _base, _i, _len, _ref;
      elem = {
        callback: callback,
        dependency_list: dependency_list
      };
      for (_i = 0, _len = dependency_list.length; _i < _len; _i++) {
        dependency = dependency_list[_i];
        if ((_ref = (_base = this.registered_dependencies)[dependency]) == null) {
          _base[dependency] = [];
        }
        this.registered_dependencies[dependency].push(elem);
      }
      return this.call_if_it_is_time(elem);
    }
  };

}).call(this);
