// Generated by CoffeeScript 1.4.0
(function() {

  this.Setup = {
    "export": window,
    interface_bindings: function() {},
    initialize_function: function(init) {
      if (is_pg()) {
        return document.addEventListener('deviceready', (function() {
          return init('Phonegap');
        }), false);
      } else {
        return $(function() {
          return init('Browser');
        });
      }
    },
    layout: function() {
      return Setup["export"]._mouse = new Mouse();
    },
    core: function() {
      Navigation.init();
      Validator.init();
      Setup["export"]._db = new Database;
      return Setup["export"]._router = new Router;
    },
    models: function(args) {},
    cache: function() {}
  };

}).call(this);
