// Generated by CoffeeScript 1.4.0
(function() {

  this.ImagePrecacher = (function() {

    function ImagePrecacher(imgs) {
      var img, _i, _len;
      for (_i = 0, _len = imgs.length; _i < _len; _i++) {
        img = imgs[_i];
        $.get(img);
      }
    }

    return ImagePrecacher;

  })();

}).call(this);
